### ISSUE TITLE
Is there a native SQS integration with Lambda?

### ISSUE THREAD

**Issue by leftdevel** [robinjmurphy/sqs-to-lambda#3]
Hi there. Apologies if this question is not appropriate here.

Wanted to ask, if it's possible to natively integrate SQS with Lambda? I see you mention in the readme that now SNS has support for Lambda, but not sure if you also mean SQS?

My issue with SNS is that it would trigger a lambda function as soon as a message arrives, which will cause my lambda functions to throttle. I'm porting (to Lambda) a service that can trigger almost a thousand events every few mins. I did a stress test sending 1k events to Lambda, and I got 17 events throttled, which is unacceptable since the service requires high availability.

Wondering if SQS/SNS has such feature that would allow me to prevent throttling?
The other option I'm looking into is to use Kinesis integration with Lambda, but sounds like too much of an effort to get working just to avoid throttling.

Thanks for any input.

**Comment by robinjmurphy** [comment]
Hi @leftdevel. There's no native integration with SQS yet. 

I've not personally used Lambda at that scale, but it sounds like concurrent execution limits are what will dictate how quickly you can process events from SNS. http://docs.aws.amazon.com/lambda/latest/dg/intro-core-components.html#concurrent-executions.

It also looks like you can ask Amazon to increase this limit http://docs.aws.amazon.com/lambda/latest/dg/limits.html.

**Comment by leftdevel** [comment]
Thank a lot @robinjmurphy !
I'll implement something like you got, but in PHP since our stack runs on it. Have a great weekend.
