### ISSUE TITLE
SNS -> Lambda guarantees?

### ISSUE THREAD

**Issue by zommerfelds** [robinjmurphy/sqs-to-lambda#4]
Hi, this is a question, not a problem in your code:

As you mention in your README, AWS supports triggering Lambda from SNS:

> Update: Lambda now supports SNS notifications as an event source, which makes this hack entirely unneccessary for SNS notifcations. You might still find it useful if you like the idea of using a Lambda function to process jobs on an SQS queue.

However, it seems like Amazon doesn't provide a guarantee that messages will be delivery from SNS to Lambda. It will retry twice and then fail without any warning or persistence. Do you have any work around this issue?

**Comment by zommerfelds** [comment]
See SNS FAQ https://aws.amazon.com/sns/faqs/:

> Q: Does Amazon SNS guarantee that messages are delivered to the subscribed endpoint?
>
> When a message is published to a topic, Amazon SNS will attempt to deliver notifications to all subscribers registered for that topic. Due to potential Internet issues or Email delivery restrictions, sometimes the notification may not successfully reach an HTTP or Email end-point. In the case of HTTP, an SNS Delivery Policy can be used to control the retry pattern (linear, geometric, exponential backoff), maximum and minimum retry delays, and other parameters. If it is critical that all published messages be successfully processed, developers should have notifications delivered to an SQS queue (in addition to notifications over other transports).

**Comment by zommerfelds** [comment]
This might be a reason to use this package instead of SNS -> Lambda. However, I'm not sure if this package has the appropriate error handling for this to be true.

**Comment by christopheblin** [comment]
Just wrting on this thread since I find it through Google

From the next point of the FAQ pointed out by @zommerfelds 

> Q: What happens to Amazon SNS messages if the subscribing endpoint is not available?
> 
> Lambda: If Lambda is not available, SNS will retry 2 times at 1 seconds apart, then 10 times exponentially backing off from 1 seconds to 20 minutes and finally 38 times every 20 minutes for a total 50 attempts over more than 13 hours before the message is discarded from SNS. 

So I would say that this is more than enough for most cases

**Comment by zommerfelds** [comment]
@christopheblin thanks for the clarification.
I feel like 13h might not be long enough for lots of low priority applications. E.g. you get a problem on off hours, and before you even get back to work, puff, the message is gone.

**Comment by hongchangfirst** [comment]
Maybe customized retry policies and something like DLQ is better?

**Comment by zommerfelds** [comment]
@hongchangfirst 
Yeah I think a DLQ will work for most purposes.

With respect to my original questions, I don't think you can define a DLQ on the SNS side. Also the SNS retry policy for Lambda doesn't look configurable.
Once your Lambda is invoked of course you can configure a DLQ but I think part of the discussion here was about if Lambda is down or if your function doesn't have a DLQ.
